### ISSUE TITLE
user.load() raises IndexError with certain profile(s)

### ISSUE THREAD

**Issue by Brawl345** [pushrbx/python3-mal#23]
When I try to load the profile of the user "[Centzilius](https://myanimelist.net/profile/Centzilius)" with
```
session.user('Centzilius').load()
```
(where `session` is a valid `Session()`)
python3-mal raises an IndexError:
```
  File "C:\Users\USER\PycharmProjects\nextbot\plugins\mal.py", line 194, in get_user
    user = self.session.user(query).load()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\myanimelist\user.py", line 639, in load
    self.set(self.parse(utilities.get_clean_dom(user_profile)))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python36\lib\site-packages\myanimelist\user.py", line 390, in parse
    total_match = re.match(r'/(?P<total>[0-9]+)', temp.xpath("./following-sibling::text()")[0])
IndexError: list index out of range
```

The problem is the line
```
total_match = re.match(r'/(?P<total>[0-9]+)', temp.xpath("./following-sibling::text()")[0])
```
in `user.py` - `temp.xpath("./following-sibling::text()")` returns two lists (I don't know why though). One with the correct data and an empty list:
```
['/12\n                    ·             Scored\n      -']
[]
```
If you wrap the line in a `try....except` statement and set `total_match` to `None` like this:
```
try:
    total_match = re.match(r'/(?P<total>[0-9]+)', temp.xpath("./following-sibling::text()")[0])
except IndexError:
    total_match = None
```
it seems to work, although this looks more like a workaround (I don't know which side effects it has).

**Comment by pushrbx** [comment]
Fixed it. The project will need better unit tests with mock http responses some time.
