### ISSUE TITLE
Attribute Error on calling anime_list() function

### ISSUE THREAD

**Issue by blackrosedragon2** [pushrbx/python3-mal#38]
![image](https://user-images.githubusercontent.com/35086260/58934709-e5126200-8788-11e9-9231-8fbe5d8882cc.png)
The following error occurs when the anime_list() function is called

**Comment by pushrbx** [comment]
Related to: #37
I'm assuming that you are also after the user's anime list, which is currently not working. It raises an error, and @Stonedestroyer has already pointed out a good solution for it in his issue which I will implement soon.
